### ISSUE TITLE
Workspace not starting, when java plugin 0.38.0 is enabled

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13495]
### Description
When starting workspace with java language support plugin version 0.38.0, workspace fails to start with `503 Service temporarily unavailable`.

It's because the container running `eclipse/che-remote-plugin-runner-java8:next` image is stuck in CrashLoopBackOff.

`kubectl get pod/<workspacePodName> -n che -o yaml` output: https://pastebin.com/20yVs8kw
`kubectl logs <workspacePodName -c <containerName> -n che` output:  https://pastebin.com/fBhj8Ec0

The same plugin in version 0.45.0 works just fine. We should either fix 0.38.0 (making that 0.38.1?) or remove that version from the plugins list (from che-plugin-registry)?

### Reproduction Steps
* Create workspace from "Che 7" Stack,
* Do not start it yet
* Edit workspace -> enable `Language Support for Java(TM) (redhat publisher) 0.38.0` plugin.
* Start workspace
* FAIL - workspace fails to start with browser saying `503 Service temporarily unavailable`

Screencast of this failure: https://youtu.be/BP4V2kIgaoE

**OS and version:**    
che.openshift.io (7.0.0-RC-1.0)
Che 7.0.0.RC2-SNAPSHOT deployed on minikube

**Diagnostics:**

**Comment by tsmaeder** [comment]
@looks like this is a OOM issue. Until recently, we were not able to set default container sizes for vscode extension che 7 plugins. @svor any idea why this would work with 0.43, but not 0.38?

@rhopp since you explicityl need to enable an old version of the plugin to make this happen, is this _really_ a P1?

**Comment by slemeur** [comment]
@tsmaeder when default stacks are not working out of the box, yes that's a P1

**Comment by svor** [comment]
@tsmaeder the problem is here because old plugins like 0.38 don't contain the information about `memoryLimit`. This problem should be fixed by https://github.com/eclipse/che/issues/13521

**Comment by tsmaeder** [comment]
> @tsmaeder when default stacks are not working out of the box, yes that's a P1

That is not the case here: he uses a default stack, then explicitly changes the resulting configuration to use an old plugin version. The most recent one works out of the box.

**Comment by Katka92** [comment]
@tsmaeder I tried to create Java Maven stack [1] and the plugin 0.38.0 was selected as a default one.

[1]  
![Screenshot from 2019-06-18 07-28-58](https://user-images.githubusercontent.com/29278800/59655563-0caaf680-919b-11e9-9497-b817a618c03d.png)

**Comment by tsmaeder** [comment]
Also true, but still not what Radim actually did in his scenario.

**Comment by tsmaeder** [comment]
@rhopp can we close this one?

**Comment by tsmaeder** [comment]
@rhopp ping?
