### ISSUE TITLE
Che-server fails to bootstrap on minikube

### ISSUE THREAD

**Issue by schwingkopf** [eclipse-che/che#15069]
### Describe the bug
Che7 deployment on my local machine failes at step "Che Pod Bootstrap" when executing:
chectl server:start --platform minikube -a operator

Error message:
Error: ERR_TIMEOUT: Timeout set to pod ready timeout 130000
    at KubeHelper.<anonymous> (C:/chectl/lib/api/kube.js:614:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:/chectl/node_modules/tslib/tslib.js:107:62)

### Che version
chectl/7.3.1 win32-x64 node-v10.17.0
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. install kubectl: v1.16.0
2. install minikube: v1.4.0 commit: 7969c25a98a018b94ea87d949350f3271e9d64b6
3. download latest chectl from https://github.com/che-incubator/chectl/releases and unpack.
4. run "minikube start --memory=4096 --cpus=2"
5. run "chectl server:start --platform minikube -a operator"
6. See error

### Expected behavior
Che Pod Bootstrap should work without error.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

>kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

>minikube version
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6

### Screenshots
Error message:
![grafik](https://user-images.githubusercontent.com/3587644/68071319-b6b9a280-fd79-11e9-94c3-7a797dea60dc.png)

Minikube dashboard:
![grafik](https://user-images.githubusercontent.com/3587644/68071593-16b14880-fd7c-11e9-947e-f1c8f206676a.png)

Pods dashboard:
![grafik](https://user-images.githubusercontent.com/3587644/68071540-a99db300-fd7b-11e9-9a36-ef923210d190.png)

Log in pod:
![grafik](https://user-images.githubusercontent.com/3587644/68071566-dd78d880-fd7b-11e9-83a7-0f72c99a138e.png)

Pod yaml:
kind: Pod
apiVersion: v1
metadata:
  name: che-5f694748b6-nbcrw
  generateName: che-5f694748b6-
  namespace: che
  selfLink: /api/v1/namespaces/che/pods/che-5f694748b6-nbcrw
  uid: bec7130c-a0c0-446c-9744-ad45ffc0274c
  resourceVersion: '4014'
  creationTimestamp: '2019-11-02T12:50:30Z'
  labels:
    app: che
    component: che
    pod-template-hash: 5f694748b6
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: che-5f694748b6
      uid: 633237a2-0c8a-4f41-aa01-ab64f7a03e35
      controller: true
      blockOwnerDeletion: true
spec:
  volumes:
    - name: che-token-824sn
      secret:
        secretName: che-token-824sn
        defaultMode: 420
  containers:
    - name: che
      image: 'eclipse/che-server:7.3.1'
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: http-debug
          containerPort: 8000
          protocol: TCP
        - name: jgroups-ping
          containerPort: 8888
          protocol: TCP
      envFrom:
        - configMapRef:
            name: che
      env:
        - name: CM_REVISION
          value: '1708'
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CHE_SELF__SIGNED__CERT
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 512Mi
      volumeMounts:
        - name: che-token-824sn
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        httpGet:
          path: /api/system/state
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 200
        timeoutSeconds: 3
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /api/system/state
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 25
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 18
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: che
  serviceAccount: che
  nodeName: minikube
  securityContext:
    runAsUser: 1724
    fsGroup: 1724
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2019-11-02T12:50:30Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2019-11-02T12:50:30Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [che]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2019-11-02T12:50:30Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [che]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2019-11-02T12:50:30Z'
  hostIP: 10.0.2.15
  podIP: 172.17.0.10
  podIPs:
    - ip: 172.17.0.10
  startTime: '2019-11-02T12:50:30Z'
  containerStatuses:
    - name: che
      state:
        running:
          startedAt: '2019-11-02T13:17:34Z'
      lastState:
        terminated:
          exitCode: 137
          reason: Error
          startedAt: '2019-11-02T13:13:14Z'
          finishedAt: '2019-11-02T13:17:34Z'
          containerID: >-
            docker://fdf0383bdaae7abd53d5ac2f5d073d4e4109bf810cd47edad08069f0efa5faa1
      ready: false
      restartCount: 6
      image: 'eclipse/che-server:7.3.1'
      imageID: >-
        docker-pullable://eclipse/che-server@sha256:5c18e9a6a2b61b022523ea03e30d8a0deb4e9a03f2a7703007c1b71ececadca6
      containerID: >-
        docker://257151a9a408dc1c792c3b2310cea96c22718caf605a8e91cac854e03110462c
      started: true
  qosClass: Burstable

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [x] my computer 
       - [x] Windows (10 Home, 1809, buil 17763.805)
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
I'm running minikube in Oracle VirtualBox on top of Windows 10 Home.

I tried with different versions of cubectl (also the nightly) and it always fails when starting the che-server. A week ago I had a che7 version running correctly and I could use the Theia editor and create workspaces on the same local machine as I get errors now. After reboot it stopped working and every try to reinstall freshly did result in the same (above described) error. Also complete reinstall of kubectl & minikube (variety of version combinations) did not solve the issue yet.

**Comment by skabashnyuk** [comment]
@schwingkopf thank you for your report. Could you please provide the whole che-server log?

**Comment by schwingkopf** [comment]
@skabashnyuk thanks for taking a look into the issu.

See attached for the full che-server log. 
[che_server_pod_log.txt](https://github.com/eclipse/che/files/3800736/che_server_pod_log.txt)

In the meanwhile I switched to the latest stable releases of minikube and kubectl with the same error:
C:\Users\Matthias>minikube version
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty

C:\Users\Matthias>kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by skabashnyuk** [comment]
This is a first error on workspace startup.
```
2019-11-02 16:53:47,543[ost-startStop-1]  [INFO ] [o.e.c.m.k.s.KeycloakSettings 91]     - Retrieving OpenId configuration from endpoint: http://keycloak-che.192.168.99.100.nip.io/auth/realms/che/.well-known/openid-configuration

2019-11-02 16:53:47,705[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 182]  - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-che.192.168.99.100.nip.io/auth/realms/che/.well-known/openid-configuration
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:70)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:53)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
    for the 1st parameter of org.eclipse.che.multiuser.keycloak.server.KeycloakProfileRetriever.<init>(KeycloakProfileRetriever.java:39)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakProfileRetriever.class(KeycloakProfileRetriever.java:32)
```
Can you check if ttp://keycloak-che.192.168.99.100.nip.io/auth/realms/che/.well-known/openid-configuration accessible? 
What is the state of keycloak deployment?

**Comment by schwingkopf** [comment]
http://keycloak-che.192.168.99.100.nip.io/auth/realms/che/.well-known/openid-configuration does not respond. Although the keycloak pod appears to be alive:
![grafik](https://user-images.githubusercontent.com/3587644/68076279-eafd8500-fdb2-11e9-9521-cd6d50c3e043.png)

Here is the log: 
[keycloak_log.txt](https://github.com/eclipse/che/files/3800896/keycloak_log.txt)

**Comment by mmorhun** [comment]
@schwingkopf I think that the bug is fixed now. Could you try to run please:
```bash
chectl server:start --platform=minikube --installer=operator --multiuser --self-signed-cert
```
and say if it works for you?

**Comment by Roshani30** [comment]
I am also facing similar issue with k8s platform
Its facing at post installation step
I checked POD and found that PV is not present and PVC is unable to bound and its only reason for failing
Do I need create PV here ?

root@osboxes:~# chectl server:start --platform=k8s --installer=operator --domain=${CHE_DOMAIN}.nip.io --self-signed-cert --cheimage=eclipse/che-server:6.13.0
✔ Verify Kubernetes API...OK
✔ 👀 Looking for an already existing Eclipse Che instance
✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
✔ ✈️ Kubernetes preflight checklist
✔ Verify if kubectl is installed
✔ Verify remote kubernetes status...done.
✔ Check Kubernetes version: Found v1.18.1.
✔ Verify domain is set...set to 10.103.253.119.nip.io.
✔ Check if cluster accessible... ok
Eclipse Che logs will be available in '/tmp/chectl-logs/1587649892261'
✔ Start following logs
✔ Start following Operator logs...done
✔ Start following Eclipse Che logs...done
✔ Start following Postgres logs...done
✔ Start following Keycloak logs...done
✔ Start following Plugin registry logs...done
✔ Start following Devfile registry logs...done
✔ Start following events
✔ Start following namespace events...done
✔ 🏃‍ Running the Eclipse Che operator
✔ Copying operator resources...done.
✔ Create Namespace (che)...It already exists.
✔ Checking for pre-created TLS secret... "che-tls" secret found
↓ Checking certificate [skipped]
✔ Create ServiceAccount che-operator in namespace che...It already exists.
✔ Create Role che-operator in namespace che...It already exists.
✔ Create ClusterRole che-operator...It already exists.
✔ Create RoleBinding che-operator in namespace che...It already exists.
✔ Create ClusterRoleBinding che-operator...It already exists.
✔ Create CRD checlusters.org.eclipse.che...It already exists.
✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
✔ Create deployment che-operator in namespace che...It already exists.
✔ Create Eclipse Che cluster eclipse-che in namespace che...It already exists.
❯ ✅ Post installation checklist
❯ Eclipse Che pod bootstrap
✖ scheduling
→ ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
downloading images
starting
Retrieving Eclipse Che server URL
Eclipse Che status check
› Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
› Installation failed, check logs in '/tmp/chectl-logs/1587649892261'
root@osboxes:/tmp/chectl-logs/1587649892261/che# cat events.txt
LAST SEEN TYPE REASON OBJECT MESSAGE
31m Warning FailedScheduling pod/postgres-5487c96577-cbn54 running "VolumeBinding" filter plugin for pod "postgres-5487c96577-cbn54": pod has unbound immediate PersistentVolumeClaims
5s Warning FailedScheduling pod/postgres-5659c44979-4kjds running "VolumeBinding" filter plugin for pod "postgres-5659c44979-4kjds": pod has unbound immediate PersistentVolumeClaims
67s Normal SuccessfulCreate replicaset/postgres-5659c44979 Created pod: postgres-5659c44979-4kjds
2m5s Warning FailedScheduling pod/postgres-6fc887f4b9-gwz76 running "VolumeBinding" filter plugin for pod "postgres-6fc887f4b9-gwz76": pod has unbound immediate PersistentVolumeClaims
77s Warning FailedScheduling pod/postgres-6fc887f4b9-gwz76 skip schedule deleting pod: che/postgres-6fc887f4b9-gwz76
30m Normal SuccessfulCreate replicaset/postgres-6fc887f4b9 Created pod: postgres-6fc887f4b9-gwz76
3m32s Normal FailedBinding persistentvolumeclaim/postgres-data no persistent volumes available for this claim and no storage class is set
30m Normal ScalingReplicaSet deployment/postgres Scaled up replica set postgres-6fc887f4b9 to 1
67s Normal ScalingReplicaSet deployment/postgres Scaled up replica set postgres-5659c44979 to 1
1s Warning FailedScheduling pod/postgres-5659c44979-4kjds running "VolumeBinding" filter plugin for pod "postgres-5659c44979-4kjds": pod has unbound immediate PersistentVolumeClaims
0s Normal FailedBinding persistentvolumeclaim/postgres-data no persistent volumes available for this claim and no storage class is set
1s Warning FailedScheduling pod/postgres-5659c44979-4kjds running "VolumeBinding" filter plugin for pod "postgres-5659c44979-4kjds": pod has unbound immediate PersistentVolumeClaims
1s Warning FailedScheduling pod/postgres-5659c44979-4kjds running "VolumeBinding" filter plugin for pod "postgres-5659c44979-4kjds": pod has unbound immediate PersistentVolumeClaims
0s Warning FailedScheduling pod/postgres-5659c44979-4kjds running "VolumeBinding" filter plugin for pod "postgres-5659c44979-4kjds": pod has unbound immediate PersistentVolumeClaims
0s Normal FailedBinding persistentvolumeclaim/postgres-data no persistent volumes available for this claim and no storage class is set
0s Warning FailedScheduling pod/postgres-5659c44979-4kjds running "VolumeBinding" filter plugin for pod "postgres-5659c44979-4kjds": pod has unbound immediate PersistentVolumeClaims

Awaiting for solution or any Idea to fix it### ###

**Comment by tolusha** [comment]
6.x version isn't supported
Just remove ` --cheimage` flag.

**Comment by Roshani30** [comment]
Hi @tolusha 
I am still getting error can you please help me what am doing wrong here 
# chectl server:start --platform=k8s --installer=operator --domain=10.101.52.51.nip.io --self-signed-cert
Set current context to 'kubernetes-admin@kubernetes'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify remote kubernetes status...done.
    ✔ Check Kubernetes version: Found v1.18.2.
    ✔ Verify domain is set...set to 10.101.52.51.nip.io.
    ↓ Check if cluster accessible [skipped]
Eclipse Che logs will be available in '/tmp/chectl-logs/1587977910823'
  ✔ Start following logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
  ✔ 🏃‍  Running the Eclipse Che operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...It already exists.
    ✔ Checking for pre-created TLS secret... "che-tls" secret found
    ↓ Checking certificate [skipped]
    ✔ Create ServiceAccount che-operator in namespace che...done.
    ✔ Create Role che-operator in namespace che...done.
    ✔ Create ClusterRole che-operator...It already exists.
    ✔ Create RoleBinding che-operator in namespace che...done.
    ✔ Create ClusterRoleBinding che-operator...It already exists.
    ✔ Create CRD checlusters.org.eclipse.che...It already exists.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...done.
    ✔ Create Eclipse Che cluster eclipse-che in namespace che...done.
  ❯ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ❯ Keycloak pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
        downloading images
        starting
      Devfile registry pod bootstrap
      Plugin registry pod bootstrap
      Eclipse Che pod bootstrap
      Retrieving Eclipse Che server URL
      Eclipse Che status check
 ›   Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
 ›   Installation failed, check logs in '/tmp/chectl-logs/1587977910823'

**Comment by tolusha** [comment]
@Roshani30 
Let's not mix different installation in one issue. Could you create another one?

**Comment by fredcsfaria** [comment]
I have had the same issue that the original message describing the bug.
 I am  running chectl in Windows 7 , Virtual Box, and  Minikube .    I tried to run  as @mmorhun  suggested but I got the same error. Is there any workaround ?
thank you

C:\Users\fcharles>chectl server:start --platform=minikube --installer=operator -
-multiuser --self-signed-cert
> Current Kubernetes context: 'minikube'
  V Verify Kubernetes API...OK
  V ?  Looking for an already existing Eclipse Che instance
    V Verify if Eclipse Che is deployed into namespace "che"...it is not
  V ??  Minikube preflight checklist
    V Verify if kubectl is installed
    V Verify if minikube is installed
    V Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    V Check Kubernetes version: Found v1.18.2.
    V Verify if minikube ingress addon is enabled
    V Enable minikube ingress addon
    V Retrieving minikube IP and domain for ingress URLs...192.168.99.101.nip.i
o.
    ↓ Check if cluster accessible [skipped]
Eclipse Che logs will be available in 'fileXXX`
tl-logs\1590431385963'
  V Start following logs
    V Start following Operator logs...done
    V Start following Eclipse Che logs...done
    V Start following Postgres logs...done
    V Start following Keycloak logs...done
    V Start following Plugin registry logs...done
    V Start following Devfile registry logs...done
  V Start following events
    V Start following namespace events...done
 »   Warning: You can also use features rich 'OLM' installer to deploy Eclipse
 »   Che.
  V ??  Running the Eclipse Che operator
    V Copying operator resources...done.
    V Create Namespace (che)...It already exists.
    ↓ Checking certificate [skipped]
    V Create ServiceAccount che-operator in namespace che...It already exists.
    V Create Role che-operator in namespace che...It already exists.
    V Create ClusterRole che-operator...It already exists.
    V Create RoleBinding che-operator in namespace che...It already exists.
    V Create ClusterRoleBinding che-operator...It already exists.
    V Create CRD checlusters.org.eclipse.che...It already exists.
    V Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    V Create deployment che-operator in namespace che...It already exists.
    V Create Eclipse Che cluster eclipse-che in namespace che...It already exis
ts.
  > ?  Post installation checklist
    > Eclipse Che pod bootstrap
      × scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false,
 .
        downloading images
        starting
      Retrieving Eclipse Che server URL
      Eclipse Che status check
    Retrieving Che self-signed CA certificate
 »   Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000.
 »   podExist: false, currentPhase: undefined
 »   Installation failed, check logs in

**Comment by ericwill** [comment]
> I have had the same issue that the original message describing the bug.
> I am running chectl in Windows 7 , Virtual Box, and Minikube . I tried to run as @mmorhun suggested but I got the same error. Is there any workaround ?
> thank you
> 
> C:\Users\fcharles>chectl server:start --platform=minikube --installer=operator -
> -multiuser --self-signed-cert
> 
> > Current Kubernetes context: 'minikube'
> > V Verify Kubernetes API...OK
> > V ?  Looking for an already existing Eclipse Che instance
> > V Verify if Eclipse Che is deployed into namespace "che"...it is not
> > V ??  Minikube preflight checklist
> > V Verify if kubectl is installed
> > V Verify if minikube is installed
> > V Verify if minikube is running
> > ↓ Start minikube [skipped]
> > → Minikube is already running.
> > V Check Kubernetes version: Found v1.18.2.
> > V Verify if minikube ingress addon is enabled
> > V Enable minikube ingress addon
> > V Retrieving minikube IP and domain for ingress URLs...192.168.99.101.nip.i
> > o.
> > ↓ Check if cluster accessible [skipped]
> > Eclipse Che logs will be available in 'fileXXX`
> > tl-logs\1590431385963'
> > V Start following logs
> > V Start following Operator logs...done
> > V Start following Eclipse Che logs...done
> > V Start following Postgres logs...done
> > V Start following Keycloak logs...done
> > V Start following Plugin registry logs...done
> > V Start following Devfile registry logs...done
> > V Start following events
> > V Start following namespace events...done
> > »   Warning: You can also use features rich 'OLM' installer to deploy Eclipse
> > »   Che.
> > V ??  Running the Eclipse Che operator
> > V Copying operator resources...done.
> > V Create Namespace (che)...It already exists.
> > ↓ Checking certificate [skipped]
> > V Create ServiceAccount che-operator in namespace che...It already exists.
> > V Create Role che-operator in namespace che...It already exists.
> > V Create ClusterRole che-operator...It already exists.
> > V Create RoleBinding che-operator in namespace che...It already exists.
> > V Create ClusterRoleBinding che-operator...It already exists.
> > V Create CRD checlusters.org.eclipse.che...It already exists.
> > V Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
> > V Create deployment che-operator in namespace che...It already exists.
> > V Create Eclipse Che cluster eclipse-che in namespace che...It already exis
> > ts.
> > ?  Post installation checklist
> > > Eclipse Che pod bootstrap
> > × scheduling
> > → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false,
> > .
> > downloading images
> > starting
> > Retrieving Eclipse Che server URL
> > Eclipse Che status check
> > Retrieving Che self-signed CA certificate
> > »   Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000.
> > »   podExist: false, currentPhase: undefined
> > »   Installation failed, check logs in

I think you're experiencing a different bug, I have the same issue and I opened #17013 for it.
