### ISSUE TITLE
Eclipse Che on Openshift probe failed

### ISSUE THREAD

**Issue by jaypal17** [eclipse-che/che#16635]
Describe bug
I am attempting to install eclipse che operator in Openshift. All resoucres appear to be fine with the exception of the che pod itself. In the event timeline there is a msg of "Liveness probe failed: HTTP probe failed with statuscode: 500" and "Readiness probe failed: HTTP probe failed with statuscode: 500". 
I have also attempted to install eclipse che following the documentation under Openshift V4 https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/
However following this I run into the issue of 
Error: Error: E_PLATFORM_NOT_READY
 »   Installation failed, check logs in

Che version = 7.10.0

Steps to reproduce
Openshift Web Console
Create new project
Install Eclipse Che operator
Create new instance of eclipse che
Turn off OpenShift oAuth
wait for resources to install
check che pod status "running" readiness "ContainersNotReady"
check event timeline Liveness probe failed: HTTP probe failed with statuscode: 500 and Readiness probe failed: HTTP probe failed with statuscode: 500
Going to link for che shows "Application is not available"

Expected 
Che to be running and can access through route

Runtime
$ oc version
Client Version: v4.3.0
Server Version: 4.3.0
Kubernetes Version: v1.16.2
crc version: 1.6.0+8ef676f

Installation method
 Tried both chectl and openshift operator method
chectl - steps under  Deploying Che with self-signed TLS certificates on OpenShift 4 using Operator
https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/

Environment
Windows - 10 v 1903

Che Log
[che-646c9479c9-lrtx2-che (2).log](https://github.com/eclipse/che/files/4489308/che-646c9479c9-lrtx2-che.2.log)

**Comment by tolusha** [comment]
@jaypal17 
Could you try to install che 7.11.0 using the latest version of chectl? 
Several bugs have been fixed since 7.10.x related to tls.

```bash
chectl update stable
```

**Comment by sleshchenko** [comment]
@jaypal17 Also could you fill in issue with the bug template https://github.com/eclipse/che/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
I assume you have self-signed certificate on you installation but you missed the corresponding flag during deploying. You can try to modify your CheCluster CR(oc edit checluster eclipse-che -n che) and put `true` for self-signed cert there https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml#L35

**Comment by jaypal17** [comment]
I tried both of your solutions and still had the same issue, I also noticed this msg:
Readiness probe failed: Get http://10.128.0.39:8080/api/system/state: dial tcp 10.128.0.39:8080: connect: connection refused
I believe the issue with my certs because I made another instance of the project and disabled TLS mode and Eclipse Che is now working. I will close the issue, and continue to troubleshoot my certs. 
Also want to mention @tolusha 7.10 is the version that the Openshift Operator hub is using. It appears 7.11 came about not that long ago so I am wondering when it will update on their end or if there is a way to force it to update to 7.11 I ran "chectl update staable" on my host machine and tried to follow this again:
https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/
but gave me this still
Error: Error: E_PLATFORM_NOT_READY
» Installation failed, check logs in
Just wanted to mention it in case I missed something. Thank you for your help!
