### ISSUE TITLE
Unable to create workspaces

### ISSUE THREAD

**Issue by robhardt** [eclipse-che/che#240]
free-standing local installation, OSX El Capitan, eclipse-che-4.0.0-RC1-SNAPSHOT, java 1.8.0_65-b17
1.  ./bin/che.sh
2.  pont browser to localhost:8080
3.  new workspace, using recipe, ready-to-go-stack, java, 1G, click 'create'
4.  creates successfully.
5.  'run in IDE'
6.  it gets to step 3, and get the error message: [STDERR] unzip:  cannot find or open /mnt/che/ws-agent.zip, /mnt/che/ws-agent.zip.zip or /mnt/che/ws-agent.zip.ZIP. (see screenshot).
7.  eventually get a 'workspace agent not responding' error.

Thanks for the help!

<img width="859" alt="screen shot 2016-01-29 at 1 28 21 am" src="https://cloud.githubusercontent.com/assets/2475365/12669636/bd2f9ab2-c627-11e5-8a19-6b515b2efd88.png">

**Comment by garagatyi** [comment]
Please specify your VM OS, VM OS version, docker version. If VM OS is RHEL, CentOS, Fedora check if  SeLinux is enabled (output of `sestatus` tool).

**Comment by ghost** [comment]
Can you please run `ls` in /eclipse-che-4.0.0-RC1-SNAPSHOT/lib

There should be ws-agent.zip and terminal there.

**Comment by randywallace** [comment]
whaaa, I ran into this too.

This is off of the codenvy/che:latest docker image

Here is the output of /mnt/che inside the (failed) workspace.. note that both 'files' are there, but they are directories!? 

```
user@0f652b786c7c:/opt$ ls -lah /mnt/che/
total 16K
drwxr-xr-x 4 root root 4.0K Jan 29 21:38 .
drwxr-xr-x 3 root root 4.0K Jan 29 21:38 ..
drwxr-xr-x 2 root root 4.0K Jan 29 21:38 terminal
drwxr-xr-x 2 root root 4.0K Jan 29 21:38 ws-agent.zip
```

and on che, the agent and terminal seem to be in the correct spot:

```
user@4be54c874268:~/che/lib$ ls -lahR /home/user/che/lib/
/home/user/che/lib/:
total 77M
drwxrwxr-x  4 user user 4.0K Jan 29 21:30 .
drwxr-xr-x 18 user user 4.0K Jan 29 21:30 ..
drwxrwxr-x  2 user user 4.0K Jan 29 21:30 terminal
-rw-rw-r--  1 user user  77M Jan 29 19:34 ws-agent.zip

/home/user/che/lib/terminal:
total 7.3M
drwxrwxr-x 2 user user 4.0K Jan 29 21:30 .
drwxrwxr-x 4 user user 4.0K Jan 29 21:30 ..
-rw-rw-r-- 1 user user 2.5K Jan 25 20:37 index.html
-rw-rw-r-- 1 user user 148K Jan 25 20:37 term.js
-rwxrwxr-x 1 user user 7.1M Jan 25 20:37 terminal
```

**Comment by amiga23** [comment]
I do have the same issue on MacOS X 10.11.3 with eclipse-che-4.0.0-beta-13-1.
I tried to create a simple workspace with Ubuntu.

**Comment by TylerJewell** [comment]
@eivantsov This one is for you.  If we can do a live diagnostic session, this may help.

**Comment by ghost** [comment]
@robhardt @amiga23 what is your Docker Machine version? Can you run docker-machine update and try it again?

Also, did you use an installer or download binaries/build from source? And where are Che binaries located? Which directory? In Users/ or outside Users?

You may also wan to ssh into a VM, and check if /lib got mounted from MacOS into the VM.

A good number of our engineers use Eclipse Che on MacOS daily.

@randywallace I cannot reproduce it on Linux. What is your OS and can you repeatedly reproduce the issue?

**Comment by randywallace** [comment]
@eivantsov  This is specifically an issue in how the API in the workspace master is launching the volume bind into the workspace slave so the slave has access to those files.  If the files are not bind-able (i.e. they do not exist), docker will create those missing files as empty folders (which kinda makes sense, docker will try to create directories if they do not exist to satisfy the bind, on both the host and container, and `/path/path/file.zip/` is a valid path).  Ideally, before the WS Master launches a container, it should make sure all the assets exist prior to launching the container and throw an exception.  Now _why_ those files do not exist is a mystery as I no longer have a copy of that particular image in my local docker server.   I've screwed with things quite a bit since posting in this issue, and have not since been able to replicate this particular problem.  As such, I suspect strongly that somehow some angry image ended up in the docker hub that was missing the workspace client dependency files after an incomplete maven build, but was fixed at some point by a new pushed image to the hub when someone identified that the image was bad.

https://github.com/codenvy/che-plugins/blob/c2d9d840a8db5f8603b38472f939f5d3c4f27f26/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/ExtServerVolumeProvider.java#L40

and

https://github.com/codenvy/che/blob/f4ffd10a1471f3c64b04f3dcdfb9ec672eed372f/assembly-ide-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L81

indicate that the workspace client startup would be something like `docker run -v /path/to/ws-agent.zip:/path/to/ws-agent.zip:ro image command` which is fine, as long as that file exists.  This problem _will_ occur every time, without a failed client container startup, _if_ that file does not in fact exist.

Some of the observations I make over here would also help alleviate this: #244 .. insofar that those assets should not me bound to a container (forcing the slaves to run on the same host as the master, unless you're using a multi-host volume driver, but this brings abundant complexity) but instead hosting them on an API Endpoint at the workspace master.

Regarding the issue that @robhardt was experiencing, running che locally on OS X outside docker-machine, I would recommend confirming that the machine.server.ext.archive and machine.server.terminal.archive configs are set correctly, and that there are assets in there for the workspace client to use.  I know from experience that running the documented build instructions via maven will generate those assets correctly.

**Comment by ghost** [comment]
Yes, docker will create those on the host and mount empty directories. And yes, the command line is correct. Let's see how far we can advance in investigating these failures on MacOS.

My only suspicion is that these resources never ended up in a VM, thus when a workspace container started, they never ended up there as well, and consequently unzip exec exited with an error.

Another possible reason, is that che-home variable wasn't set correctly, thus an absolute path to ws-agent turned out to be non-existent.

@amiga23 @robhardt if possible, can you perform the following?
1. SSH into a VM
2. Launch Che as usual, try to create a workspace
3. Just after a container starts, in a VM, run

get workspace container ID
`docker ps`

get information on bindings and mounts
`docker inspect --format '{{ .Mounts}}'` $containerID
`docker inspect --format '{{.HostConfig.Binds}}' $containerID`

Also, as already said, try to SSH into a VM and make sure that Che directory with `/lib` is there (find out permissions as well)

**Comment by robhardt** [comment]
@eivantsov - I think I found the issue.  In my case, I was running che from an external drive.  docker-machine's boot2docker vm doesn't mount external volumes, in fact, it appears only to mount the 'Users' directory from the host machine.

At some point in the process the 'ws-agent.zip' and 'terminal' got created as directories as per @randywallace 's observation.  It would appear that somewhere in the creation of the workspace image, it is assumed that ws-agent.zip exists and that its location in the docker-machine vm mirrors its location on the host machine.  I think this would normally be true - if the file existed under '/Users,' but not if it is under '/Volumes' or in another non-standard location.  When it wasn't found, ws-agent.zip got created as an empty directory.

BTW, I was actually working in a symlinked dir under /Users, but it must get unpacked to its canonical location at some point.

I used the script below to mount my external volume on my docker-machine instance and now I can create a workspace!  Thanks to @cristobal for the script.

https://gist.github.com/cristobal/fcb0987871d7e1f7449e

I'd be curious if this solves the problem for @randywallace  and @amiga23

**Comment by ghost** [comment]
Yes, installing Che on a Mac outside user home, will cause this error since it is only a user's home directory that gets mounted into a VM. While we do forcefully copy ws-agent.zip and terminal into `%userprofile%\AppData\Eclipse Che` on Windows, we do not do that on a Mac.

Yes, I think this will solve similar issues where people installed Che on /opt or other directories outside user home.

Since it is solved for you now, I am closing the issue.

Docs will be updated with a word of caution on where Che should not be installed on a Mac.

**Comment by VenomVendor** [comment]
Any update on docs, am still facing the same issue & am noob.
where should I install `che`?

**Comment by robhardt** [comment]
Are you on a Mac?  Anything under '/Users/<your id>/' should work out of
the box.

**Comment by VenomVendor** [comment]
Moved `che` inside `/Users/<che>` it's working now.
Unable to create workspace outside `Users`. Shows wrong error message, if I do so.

**Comment by afalak** [comment]
Get
[STDERR] unzip:  cannot find or open /mnt/che/ws-agent.zip, /mnt/che/ws-agent.zip.zip or /mnt/che/ws-agent.zip.ZIP.

Running as administrator. vagrant/chef all work fine. docker itself is fine. not che
Still being mounted wrongly even from windows 7 pro 64, che4 rc11, jdk1.8-40-b25. docker 1.10.3 vbox 4.3.12 {have DG so cannot update vbox}
Was worried about space in AppData/Local/**Eclipse Che**/. Looks like that's not a problem but can we avoid space here ? They are mounted as folders with no files. Am in GIT Bash

/apps/DockerToolbox:./docker exec 889edcad9ee1 ls -l /mnt/che/
total 0
drwxr-xr-x 2 root root 40 Mar 11 11:40 terminal
drwxr-xr-x 2 root root 40 Mar 11 11:40 ws-agent.zip

Just to check space issue I updated the WindowsHostUtils class (just _AppData/Local/Che_ now) and the jar and the war just to see, cleaned work and exploded war folders. restarted che. Saw the new folder _AppData/Local/Che_ being created with the files which are correct. But I get same error and same machine state
/home/mobaxterm/apps/DockerToolbox:./docker exec ffff10392e2a ls -l /mnt/che/
total 0
drwxr-xr-x 2 root root 40 Mar 12 06:50 terminal
drwxr-xr-x 2 root root 40 Mar 12 06:50 ws-agent.zip

How do I get these to mount properly and create a project ? Add to new issue ?

**Comment by TylerJewell** [comment]
@eivantsov Please open an issue that will have us perform the same logic checks that we do for Windows on the Mac.  I believe it is the following:
1. On windows, we print out a special overview message in `che.sh` saying where the ws must be.
2. We forcibly copy the `terminal` and `ws-agent.zip` into the right directory.
3. We should forcibly fail if the workspace directory is not `/users`.  I believe you can have che installed in other directories, but the workspace should be in `/users`.  In the `che.properties` file this would be the entry that would have to be overridden on macs.

```
# Directory where your workspaces and projects save.
# This property is currently ignored on windows due to virtual box limitation.
# On windows, always set at %userprofile%\Local\AppData\Eclipse Che\vfs.
che.user.workspaces.storage=${che.home}/workspaces 
```

**Comment by TylerJewell** [comment]
@afalak Can you provide some more details about your installation:
1. What directory is Che installed into.
2. What is the che version you are using as well.

Thanks.

**Comment by afalak** [comment]
Started new issue at [695](https://github.com/eclipse/che/issues/695)

**Comment by ayubmalik** [comment]
I can confirm that if using Mac OS X (el capitan) if you unzip to /opt folder e.g. /opt/eclipse-che
then you get the  'cannot find /mnt/che/ws-agent.zip'.

**Moving** the eclipse-che folder to a home folder e.g. /Users/<username>/che **does** get rid of the error and starts the workspace.

 This is not ideal but ok for experimenting with Che :)

**Comment by ddementieva** [comment]
This is a limitation of Virtualbox. Only user home directory gets mounted into the VM.

**Comment by TylerJewell** [comment]
@ayubmalik You have a few choices here.
1. Use the --machine-driver:fusion option when starting Che.  You will need vmware fusion installed.  We will then use Fusion to create the VM and you can have che files in directories other than /Users and it will still mount properly.
2. You can update the che.properties file to have your worksapce and project's stored in /Users but also have Che installed in another directory.  See the Configuration page in the docs for how to configure this.
3. You can install Che into /Users.

**Comment by ayubmalik** [comment]
@TylerJewell @ddementieva Thanks for the comments. I have to stick with VirtualBox for now. So I have moved che install to my home dir.

**Comment by lucaspottersky** [comment]
I'm trying to follow the docs here, but no success...

My host is a Digital Ocean Droplet running Ubuntu 14.04. I tried to follow the docker-compose for [v4.3 instructions](https://eclipse-che.readme.io/v4.3/docs/usage-docker#section-docker-compose) as well as for [v4.0 instructions](https://eclipse-che.readme.io/v4.0/docs/usage-docker#section-docker-compose) 

Additionally, I did try to change "image" to both `codenvy:che:4.3.2` and `codenvy:che:4.0.1` respectively.

No success. :(

**Comment by TylerJewell** [comment]
Please open a dedicated issue and follow the issue reporting guidelines - then an engineer is equipped to help out.
https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by Hin-Fan** [comment]
I had been trying to install Che as a container in docker for windows.  I was able to get it to work, but not fully.  First, the docker statement from the documentation does not work:

docker run --net=host
           --name=che
           --restart=always
           -v /c/che/lib:/home/user/che/lib-copy 
           -v /c/che/workspaces:/home/user/che/workspaces 
           -v /c/che/storage:/home/user/che/storage 
           -e "DOCKER_HOST=tcp://10.0.75.2:2375"
           codenvy/che

The first thing it goes wrong is:
'sudo: unable to resolve host moby: Connection timed out'
(I did found a workaround for this but it is a little complicated and this message doesn't seems to cause issues.).  

When I tried to create a project, it will fail at starting workspace agent with:

[STDERR] unzip: cannot find or open /mnt/che/ws-agent.zip, /mnt/che/ws-agent.zip.zip or /mnt/che/ws-agent.zip.ZIP.

I discovered that, although the ws-agent.zip was created in c:\che\lib, it was not visible to the workspaces container, which docker creates it as a directory instead.

I have modified the docker statement to bind everything else except che/lib:
docker run --name=che 
           --restart=always 
           --net=host --privileged 
           -v /home/user/che/lib:/home/user/che/lib-copy 
           -v /c/che/workspaces:/home/user/che/workspaces 
           -v /c/che/storage:/home/user/che/storage 
           -e "DOCKER_HOST=tcp://10.0.75.2:2375" codenvy/che

Everything seems to work and I can start a new project, but when I check c:\che\workspaces, it has the folder with the workspace name, but it is empty (the project was not there).
I started another container with ubuntu:

docker run -it -v /home:/test --name=test ubuntu

when i type ls /test/user/che, i found /lib and /workspaces and the projects were actually in the workspaces folder.

That is, it seems that both lib-copy and workspaces are binded from the che host to the docker host internally and the binding from the docker statement makes it a 3-way binding, che host, docker host and local.  After the che host has been ran, docker didn't sync these folders correctly, leaving all files stored on the docker host instead of the local.

I tried to remove the lib-copy and workspaces binding from the docker statement, but the ws-agent.zip was once again not found and docker host still contains the /home/user/che with /lib and workspaces folders, so i have to keep them.  There are 2 problems with this solution:
1) workspaces and projects are stored in the docker host, which nothing should be stored there.
2) when restarting che, all workspaces disappeared.  I need to recreate the workspaces (of the same name) for che to create a new workspace container using content stored in the docker host /home/user/che/{workspaces}

My projects are big and doesn't fit into the original Hyper-V VM.  I guess I can increase the drive size but that should only be a temporary solution.  Please educate me if there is a remedy to this.

Again, the docker statement that works without misleading binding:
 docker run --name=che 
           --restart=always 
           --net=host --privileged 
           -v /home/user/che/lib:/home/user/che/lib-copy 
           -v /home/user/che/workspaces:/home/user/che/workspaces 
           -v /c/che/storage:/home/user/che/storage 
           -e "DOCKER_HOST=tcp://10.0.75.2:2375" codenvy/che

To add che.properties to the binding, simply add :
 '-v /c/che/che.properties:/home/user/.che/che.properties'
to the docker statement.

**Comment by TylerJewell** [comment]
Hi @Hin-Fan:

Thanks for the detailed write up.  When I see the original `docker run` statement you provided, it does not match what we have in the documentation, which is:

```
docker run --net=host
           --name=che
           --restart=always
           -v /home/user/che/lib:/home/user/che/lib-copy 
           -v /home/user/che/workspaces:/home/user/che/workspaces 
           -v /home/user/che/storage:/home/user/che/storage 
           -e "DOCKER_HOST=tcp://10.0.75.2:2375"
           codenvy/che

# Che will be available at http://10.0.75.2:8080
```

Note:
1. You cannot change the location of the volume mounts.  I can go into a long explanation about it, but it's been written about in other forums and it takes a while to write about.  But it has to do with the fact that you are launching the che container inside of a moby VM.  So the mappings are not to the host but between the VM and the container.
1. Ignore the moby sudo error.  It's an unhelpful, but meaningless error right now.  It is a known error but does not cause any problems.
2. Do not set the --privileged flag.  It is not needed and opens security issues.  It is only needed if you want to build che in che.  But otherwise, it should not be used.
3.  We are working on improving the docker run syntax.  We'll eventually allow you to only have to set -v /var/run/docker.sock:/var/run/docker.sock.  The other volume mounts for workspace, project storage will be configurable with environment variables.  The lib-copy thing will go away.

**Comment by Hin-Fan** [comment]
Thank you for the quick reply.  The original docker statement was copied from https://eclipse-che.readme.io/docs/usage-docker-for-windows-beta, located slightly lower than the one that you have.  I may have mis-interpreted its meaning and usage.

Is there a solution to workspaces disappearing after restarting che?

**Comment by TylerJewell** [comment]
I think the workspaces disappearing after a restart may be an unrelated issue.  You should either create a new issue or describe your problem in another open issue that is related.  There are some other issues open on ws restarts after Che server reboots.

**Comment by Hin-Fan** [comment]
Thank you Tyler.

**Comment by wallrick** [comment]
I am having the same issue.  I think the docker run instructions are confusing and miss-leading.  Under the "MOUNT FILES TO C:\" section it seems to imply that I can mount the workspace to local "c" folder so that any workspaces are saved so if I run a newer instance my changes will be saved.  I think from the explanation above this understanding is wrong and in fact there is no way to have the files located on my Windows hyperv host.  Is this correct?  Either way the instructions need to be clarified.

**Comment by TylerJewell** [comment]
@wallrick - actually it's the opposite.  You _can_ mount the /workspaces and /storage volumes to the C:\ drive on windows.  What you cannot change is the location of the mounts for /var/run/docker.sock and for the /lib-copy directory.  I can see how the documentation doesn't make this explicit and we should fix.  

This all goes away very shortly, though, because of this nice PR:
https://github.com/eclipse/che/pull/1683/files/abd2488d704dd04fab8bad6310192bda61bdcc51#r70068924

**Comment by TylerJewell** [comment]
@wallrick - BTW, in Docker for Windows Beta, you have to modify the settings of Docker to be able to use mounts that are not located in /c/users/.  So in addition to using the mounts in the right location, you have to also update your Docker settings to use the entire C:\ drive.

**Comment by wallrick** [comment]
@TylerJewell Thanks.  I had already run into that issue.  I am making another run at this using your previous comments.  Fingers crossed.

**Comment by wallrick** [comment]
![image](https://cloud.githubusercontent.com/assets/1100578/16688692/34d4934e-44ed-11e6-8b9f-f9fef13a27ca.png)

That would be a no go...

Tried this.
PS C:\Users\rwall\Downloads\Kitematic-Windows> docker run --net=host --name=che --restart=always -v /c/Users/rwall/che/workspaces:/home/user/che/workspaces -v /c/Users/rwall/che/storage:/home/user/che/storage -e "DOCKER_HOST=tcp://10.0.75.2:2375" codenvy/che

**Comment by TylerJewell** [comment]
@wallrick your syntax is wrong.  You are missing a mandatory volume mount, which you cannot change.  The /lib-copy stuff is necessary magic for us to do our stuff internally.

```
docker run --net=host
           --name=che
           --restart=always
           -v /home/user/che/lib:/home/user/che/lib-copy 
           -v /c/users/rwall/che/workspaces:/home/user/che/workspaces 
           -v /c/users/rwall/che/storage:/home/user/che/storage 
           -e "DOCKER_HOST=tcp://10.0.75.2:2375"
           codenvy/che
```

**Comment by wallrick** [comment]
@TylerJewell Trying again.  I am resetting the Docker MobyLinuxVM as well since I original had this working when I ran this directly through Kitematic and used all the defaults however that is also now failing.  I think playing around with trying to remap the directories has left some stuff in the Docker VM which is also causing me issues.

**Comment by TylerJewell** [comment]
Good luck.  Once docker 1.13 ships for docker for win/mac/linus all of these issues disappear.  the syntax will only be: "docker run codenvy/che start".  No volume mounts and you still get to control the location of where workspaces are stored by setting an environment variable instead.

**Comment by wallrick** [comment]
@TylerJewell Deleted MobyLinuxVM from HyperV, resetting docker to push a fresh instance of the MobyLinuxVM and then running your corrected version of the run command.  Things started up but nothing in the workspaces or storage folder after creating a new workspace.  However if I connect to the MobyLinuxVM I can see the newly added workspace exists under /home/user/che/storage. 

$ ls
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
$ cd
$ ls
che
$ cd che
$ ls
LICENSE  bin   lib       plugins  stacks   templates  workspaces
README   conf  lib-copy  sdk      storage  tomcat
$ cd workspaces
$ ls
wksp-os30

**Comment by TylerJewell** [comment]
Double check in your docker for win settings that mounting is activated for the directory that you chose.
You may want to double check the C:\ syntax.  I have noticed that it's not consistent - so is it c:/, or is it /c/users/, or is it c:\users.  I know that Docker has been moving some of this stuff around.

**Comment by wallrick** [comment]
So that was one of the issues, I forgot to share the "C" drive.  
![image](https://cloud.githubusercontent.com/assets/1100578/16691895/951d7a68-44fc-11e6-9431-aa173999704e.png)

I needed to blow away the MobyLinuxVM again however even after making the change.  It's all working now.  Thanks @TylerJewell

**Comment by TylerJewell** [comment]
Great!

**Comment by Hin-Fan** [comment]
@wallrick , can you confirm that your workspace folder from your local drive contains the project please?
@TylerJewell I can't make workspace store locally.  
Note that I did replace c:\Users\rwall to my %userprofile% when I ran these code.  I kept in my post to make everything in line to the coding of this thread.

```
docker run --net=host `
           --name=che `
           --restart=always `
           -v /home/user/che/lib:/home/user/che/lib-copy `
           -v /c/users/rwall/che/workspaces:/home/user/che/workspaces `
           -v /c/users/rwall/che/storage:/home/user/che/storage `
           -e "DOCKER_HOST=tcp://10.0.75.2:2375" `
           codenvy/che 
```

After creating a project named theProject in workspace named myWS, there is a myWS is my c:\Users\rwall\che\workspaces directory, but theProject isn't in it, it is empty.

I tried to peek inside che with

```
docker exec che ls /home/user/che/workspaces/myWS
```

it is also empty.

If i peek into the host

```
docker run -v /home/user/che:/data alpine ls /data/workspaces/myWS
```

I can see theProject

I tried to create a file in /home/user/che/workspaces/myWS

```
docker exec che touch /home/user/che/workspaces/myWS/test.txt
```

it creates a test.txt in c:\Users\rwall\che\workspaces\myWS

To me, that means both the mounting of c:\ in docker and the binding from c:\Users\che\workspaces to che's \home\user\che\workspaces work.  However, the projects folder of the workspace container is not binding to it.

I did a `docker inspect` on the workspace container to see where the /projects folder was mounted to and it shows

```
...
            {
                "Source": "/home/user/che/workspaces/myWS",
                "Destination": "/projects",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            }
...
```

This binding is from /home/user/che/workspaces/myWS of the docker host, not container che, hence nothing gets stored in c:\Users\rwall\che\workspaces\myWS.

Please let me know if I mistyped anything.

**Comment by rwallinterset** [comment]
@Hin-Fan You are correct.  I see the folders but no files.

**Comment by TylerJewell** [comment]
@Hin-Fan - I am going to be running a series of tests on this today.

**Comment by TylerJewell** [comment]
@Hin-Fan - I confirm the issue.  Please use issue #1711 for tracking.

**Comment by TylerJewell** [comment]
@Hin-Fan - a fix is coming in 4.5 for early next week.  tested this morning and it worked good.
https://github.com/eclipse/che/pull/1733#issuecomment-232927503
