### ISSUE TITLE
Can't create a new workspace 

### ISSUE THREAD

**Issue by thejaay** [eclipse-che/che#431]
I'm currently running Che as a server (not run in a container) on Debian Jessy. I am using Che 4.0.0-RC3 downloaded from the eclipse website as a targz. 
The Che dashboard is working properly on 8080 so I am assuming that the configuration is good for that part, I am accessing it throught another computer.

I was also able to play with some docker container (create/delete/run...) with the same user I am launching Che with so I am also assuming that docker is properly configured too...

I try to create a new workspace from the web interface but when I press "RUN" nothing is happenning but the following output in the terminal
`2016-02-19 10:33:12,624[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 167]      - Creating machine [ws = workspacewm59mabzwnrhwg0h: env = wksp-jwl5: machine = ws-mac`

Che is running with the following command
`./che.sh -s:uid -r:x.x.x.x run`

Full execution trace with exception
![image](https://cloud.githubusercontent.com/assets/4380207/13172045/6606fe4e-d6f6-11e5-9769-de6e0ccb892a.png)
![image](https://cloud.githubusercontent.com/assets/4380207/13172084/94203a02-d6f6-11e5-8997-6b53ff6cbfa7.png)

When doing `docker ps -a` there is only my registry container, it seems like absolutely no docker command are issued from Che.
Does anybody got this error?

**Comment by ghost** [comment]
The fact that there's no workspace container has its explanation - Che server killed it having previously failed to reach it.

You use `-r:ip` because it is a remote instance?

Can you try it again but press Open in IDE instead of run - this way you will see workspace agent logs.

**Comment by thejaay** [comment]
Hi,

First, thank you for your quick response, the fact that I'm using `-r:ip` is because of what I have understood from the documentation here [https://eclipse-che.readme.io/docs/configuration](url) in the `DOCKER_MACHINE_HOST="IP"`section (from what I know using `-r:ip` overwrite this parameter but I may be wrong).

Just tested launching the server with `./che.sh -s:uid` does exactly the same error when running the workspace : 
`org.eclipse.che.api.machine.server.exception.MachineException: Can't start machine ws-machine. Connexion terminÃ©e par expiration du dÃ©lai d'attente
        at org.eclipse.che.api.machine.server.MachineManager.getRecipeByLocation(MachineManager.java:989) ~[che-core-api-machine-4.0.0-RC3.jar:4.0.0-RC3]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:293) ~[che-core-api-machine-4.0.0-RC3.jar:4.0.0-RC3]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:168) ~[che-core-api-machine-4.0.0-RC3.jar:4.0.0-RC3]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:454) ~[che-core-api-workspace-4.0.0-RC3.jar:4.0.0-RC3]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:320) ~[che-core-api-workspace-4.0.0-RC3.jar:4.0.0-RC3]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:146) ~[che-core-api-workspace-4.0.0-RC3.jar:4.0.0-RC3]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:642) ~[che-core-api-workspace-4.0.0-RC3.jar:4.0.0-RC3]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$1(WorkspaceManager.java:613) ~[che-core-api-workspace-4.0.0-RC3.jar:4.0.0-RC3]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.0-RC3.jar:4.0.0-RC3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_73]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]
`

It's like Che and docker can't communicate properly, is there a way to test this connection or somehow giving you more informations?

**Comment by ghost** [comment]
Are you running Che as a user or as a root? Also, when running `docker ps` are you doing it as root or user?

**Comment by thejaay** [comment]
I am running Che as a user, this user is in docker group. I am able to do `docker ps` with that user and other docker commands (pull, create,build...). The user got the UID 1001 that's why I'm using `-s:uid`. Is there a spcial user that run docker from Che that I need to put in the docker group or something?

I also forgot to tell you that I am running the Che server inside a virtual machine (VMWare)

**Comment by ghost** [comment]
Here's what you may try:
1. start Che
2. go to localhost:8080/ide/myworkspace
3. you will be offered to create a workspace
4. choose a predefined stack
5. copy and share recipe URl that you will see in the field below the stack

Also, you may try to launch Che and go to http://localhost:8080/ide/api/recipe/

**Comment by thejaay** [comment]
The recipe URI contain the following : 
`FROM codenvy/ubuntu_jdk8`, the creation of the workspace is OK but I still can't run it

**Comment by ghost** [comment]
What was the URL?

Can you try creating a workspace with a custom recipe - https://gist.githubusercontent.com/eivantsov/8bad5db0e987adec87d5/raw/bdd31a2bcc7e5e7803419ce10da8466f1f6e2243/Dockerfile (custom stack in the dashboard -> import custom stack)?

In addition, can you open browser's dev console and look for failed requests?

**Comment by thejaay** [comment]
Just tried your recipe and that's working, the machine is successfully created and I can see it running `docker ps`

**Comment by ghost** [comment]
What was the recipe URL when when you managed to get its content in https://github.com/eclipse/che/issues/431#issuecomment-186213885

**Comment by thejaay** [comment]
Using predefined stask "UBUNTU_JDK8" the recipe URL was http://myserver:8080/ide/api/recipe/recipe_ubuntu/script
Using "generated_java" produce
http://myserver:8080/ide/api/recipe/reciper6khrmyyh62t98cw/script

**Comment by ghost** [comment]
Can myserver be resolved within a vm? You may want to add an entry to /etc/hosts to point it to the right IP.

Also, why is it myserver? Don't you use browser in the VM? Try accessing Che by IP. This should fix it.

**Comment by thejaay** [comment]
The server running Che doesn't have any graphical interface, so I am accessing it with a browser outside the VM. I have tried accessing the dashboard with the IP both starting the server with and without `-r:x.x.x.x`.
Actually I can only run a workspace with a custom stack based on a recipe URL (thank to your previous solution), in fact I'm more worried about my networking configuration, do you have any informations about network interaction that are involved in Che (ports that need to be opened maybe?).
Thank a lot for your help

**Comment by ghost** [comment]
Can you ping myserver from within a VM? Does VM know that is is myserver? When you start a workspace, there's a recipe - http://myserver:8080/ide/api/recipe/recipe_ubuntu/script, so, machine API tries to create a machine off this recipe. If this dns cannot be resolved, it results in a failure. 

Things to try
1. SSH into a VM
2. Ping myserver:8080

Also
1. Access Che using VM IP

As to ports, if you can create a workspace using a custom recipe and the workspace runs ok, there seems to be no port issues.

**Comment by thejaay** [comment]
OK, so I am still not able to deal with ready to go stack... 
I have tried the following : creating a workspace from custom recipe, then pausing che (before container is destroyed), entering the docker machine with `docker exec -ti imgid bash`, pinging myserver is OK (DNS and IP), I am able to SSH to the container `ssh 172.17.0.3` it then asking me for handshake and password (so I guess it's OK).

I may have some more information as I have noticed something while running `netstat -nat`
Upon creating a new project (ready to go stack) I got stuck on "2 - Starting workspace master", before timeout occurs, I noticed that a new port is opened (X.X.X.X is my server public IP): 

Proto Recv-Q Send-Q Adresse locale          Adresse distante        Etat
tcp        0      0 0.0.0.0:50637           0.0.0.0:\*               LISTEN
tcp        0      0 0.0.0.0:111             0.0.0.0:\*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:\*               LISTEN
tcp        0    232 10.23.8.5:22            80.12.43.32:40715       ESTABLISHED
tcp6       0      0 :::32001                :::\*                    LISTEN
tcp6       0      0 127.0.0.1:8005          :::\*                    LISTEN
tcp6       0      0 :::32101                :::\*                    LISTEN
tcp6       0      0 :::5000                 :::\*                    LISTEN
tcp6       0      0 :::111                  :::\*                    LISTEN
tcp6       0      0 :::8080                 :::\*                    LISTEN
tcp6       0      0 :::80                   :::\*                    LISTEN
tcp6       0      0 :::44916                :::\*                    LISTEN
tcp6       0      0 :::22                   :::\*                    LISTEN
tcp6       0      0 ::1:25                  :::\*                    LISTEN
tcp6       0      0 :::51097                :::\*                    LISTEN
tcp6       0      0 10.23.8.5:8080          80.12.43.32:40978       ESTABLISHED
tcp6       0      1 10.23.8.5:53209         **X.X.X.X**:8080      SYN_SENT

Once the exception pop `2016-02-23 14:12:26,882[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 615]    - Can't start machine ws-machine. Connexion terminÃ©e par expiration du dÃ©lai d'attente` the port 53209 disappear.
I am behind a firewall, so I was wondering if there is a custom port that is used to pull images from predefined stacks.
Many thanks for your help

**Comment by eivantsov** [comment]
Can you please the suggested diagnostic steps?

And yes, the ephemeral port range has to be opened. But since you can run a workspace off a custom recipe, it should not be a problem.

**Comment by ghost** [comment]
Can the VM itself resolve myserver DNS? It is the server that cannot resolve this URL.

When in a VM can you successfully run?

`curl http://myserver:8080/ide/api/recipe/recipe_ubuntu/script`

**Comment by thejaay** [comment]
Hi,

I have resolved my problem, it has nothing to do with Eclipse software but my networking configuration, my firewall had a restrictive policy over websocket and some NAT rules were missing. I am able to run a workspace, project and open the IDE.
I am sorry for wasting your time, on the other hand I got a better understanding of the whole Che environment, again thank you for your help and your patience.

**Comment by TylerJewell** [comment]
We have - for a long time - had a vision of some sort of "intelligent network check" screen that loads inside of Che after the server boots. It would check for access to various network dependencies such as GitHub APIs and also do a deep dive web socket / TCP / UDP test to detect any errors.  @benoitf has the vision on what to do with this.  We will eventually get there, but your scenario just makes us think about whether it is too far down the backlog.

**Comment by ghost** [comment]
The issue seems to be resolved. Closing...
