### ISSUE TITLE
Running 'docker' succeeded, but 'docker ps' failed. This usually means that docker cannot reach its daemon.

### ISSUE THREAD

**Issue by linbinHades** [eclipse-che/che#795]
when I docker run dockernvy/che , I face the problem as the title show.
!!!
!!!Running 'docker' succeeded, but 'docker ps' failed. This usually means that docker cannot reach its 
!!!daemon.
who can tell me how to deal it?

**Comment by ghost** [comment]
How exactly do you run Che docker image? What is your OS and Docker version?

You may want to take a look at https://eclipse-che.readme.io/docs/usage-docker#using-docker-syntax

**Comment by linbinHades** [comment]
Hello.Thank you for you answer .I user Ubuntu 15.10 and docker 1.10.3.
In my OS , I used 
`docker run -ti --privileged --name=che --net=host -p 8080:8080 -p 32768-32788:32768-32788 -v /var/run/docker.sock:/var/run/docker.sock codenvy/che
`
Sometimes,docker can run,however,I used my friend's computer ,it did not work.

**Comment by linbinHades** [comment]
@eivantsov Hello.Thank you for you answer .I user Ubuntu 15.10 and docker 1.10.3.
 In my OS , I used 
 `docker run -ti --privileged --name=che --net=host -p 8080:8080 -p 32768-32788:32768-32788 -v /var/run/docker.sock:/var/run/docker.sock codenvy/che  `
 Sometimes,docker can run,however,I used my friend's computer ,it did not work.

**Comment by ghost** [comment]
What do you mean, sometimes docker can run?

`-p 8080:8080 -p 32768-32788:32768-32788` isn't necessary if you use --net=host. Privileged mode as well.

Can you check permissions for your local `/var/run/docker.sock` and allow others to read and write?

Also, you have to use all the mounts as per docs, otherwise a workspace won't start - https://eclipse-che.readme.io/docs/usage-docker

**Comment by ghost** [comment]
I have just started a fresh Ubuntu 15 node with the latest Docker, and found no issues running a Che image.

**Comment by linbinHades** [comment]
@eivantsov  Yes ,I mean it can run ,however,when I change another machine,it did not run .
what do you meant about 
check permissions for your local  /var/run/docker.sock  and allow others to read and write?
?
I have just started to use docker,so  I'm not familiar with it .

**Comment by ghost** [comment]
I need info on your another machine then.

As to permissions for  `/var/run/docker.sock` - you need to make sure that others can read and write. It has nothing to do with Docker at this point. Just file permissions. Run `sudo chmod 777 /var/run/docker.sock`.

**Comment by DevarajAmarnath** [comment]
I also noticed this issue. I also noticed that gid of group "docker" inside the container differs from the gid of "docker" group on my host machine.

**Comment by ghost** [comment]
Try changing permissions for `/var/run/docker.sock` or avoid mounting this file but rather export DOCKER_HOST - https://eclipse-che.readme.io/docs/usage-docker#unix-socket-mounting-vs-exporting-docker_host

**Comment by ghost** [comment]
@AmarnathDevaraj did you try changing permissions for `/var/run/docker.sock` or exporting DOCKER_HOST (see my comment above)?

**Comment by DevarajAmarnath** [comment]
Hi @eivantsov , I tried but couldn't make it work.

Here is what I did.
1. Updated  /etc/systemd/system/docker.service.d/docker.conf
   [Service]
   ExecStart=
   ExecStart=/usr/bin/docker daemon -D -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock
2. ps aux | grep docker | grep -v grep
   root     10364  0.1  0.6 589808 17660 ?        Ssl  09:06   0:00 /usr/bin/docker daemon -D -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock
3. Checked http://10.0.3.15:2376/containers/json
   The page displayed "[]"
4. ls -la /var/run/docker.sock 
   srw-rw----. 1 root docker 0 Mar 31 09:06 /var/run/docker.sock
5. docker run -ti --net=host -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage -e "DOCKER_HOST=tcp://10.0.3.15:2376"  codenvy/che
6. Received the same error.
   !!!
   !!! Running 'docker' succeeded, but 'docker ps' failed. This usually means that docker cannot reach its daemon.
   !!!
7. I also tried adding mode 777 on file /var/run/docker.sock. But still the same error.
   srwxrwxrwx. 1 root docker 0 Mar 31 09:06 /var/run/docker.sock

I am running  centos-release-7-2.1511.el7.centos.2.10.x86_64 on a virtual box.

**Comment by ghost** [comment]
You do not need `-v /var/run/docker.sock` in this case. Remove it.

Another way to test it is to run:

`docker run -ti -e "DOCKER_HOST=tcp://10.0.3.15:2375" codenvy/che bash` and once in a container run:

`docker ps` This way you will see the actual output from Docker. You need to make sure that 10.0.3.15 can be actually reached from within the container.

**Comment by ghost** [comment]
I have tried it both ways with a clean Centos 7.1 machine. Allowed read and write for others for docker.sock. And tried exporting DOCKER_HOST. It worked for me both ways.

**Comment by DevarajAmarnath** [comment]
Here is the output of http://10.0.3.15:2376/containers/json

[{"Id":"1d8f7cec8f1ff912bc2cc6803b7de8c70fc4f150d8b2a95e6cd9a7a2ff0d3cfd","Names":["/sad_shockley"],"Image":"codenvy/che","Command":"bash","Created":1459434941,"Ports":[{"PrivatePort":8080,"Type":"tcp"}],"Labels":{},"Status":"Up 23 seconds","HostConfig":{"NetworkMode":"default"}}]

Inside the container I'm getting this error:

docker run -ti -e "DOCKER_HOST=tcp://10.0.3.15:2376" codenvy/che bash
user@1d8f7cec8f1f:/$ 
user@1d8f7cec8f1f:/$ docker ps
An error occurred trying to connect: Get http://10.0.3.15:2376/v1.21/containers/json: dial tcp 10.0.3.15:2376: no route to host

**Comment by ghost** [comment]
It means that the IP is unreachable from within the container. Is this your VM IP? You may want to give it a try with docker0 IP.

**Comment by DevarajAmarnath** [comment]
I did try with both the IP's. I can also ping both the IP's. It looks like I cannot reach that specific port. I also disabled SELinux since there was a notification that dockers was accessing some port. I will try to debug more this weekend and let you know. 

Thank you very much for helping me out on this one. I am learning more about docker just by debugging this.:)

**Comment by ghost** [comment]
@AmarnathDevaraj  any update?

**Comment by DevarajAmarnath** [comment]
Hello @eivantsov, I disabled the firewall on my VM and now I can reach the port. :+1: 

But get a different error,  which I think is related to the issue below.
https://github.com/docker/machine/issues/2147

I think updating docker should fix it.

**Comment by AmarnathDevaraj** [comment]
No luck yet.

[amarnath@localhost ~]$ docker run -ti -e "DOCKER_HOST=tcp://10.0.3.15:2375"  codenvy/che bash
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
user@10d22a5215fe:/$ 
user@10d22a5215fe:/$ 
user@10d22a5215fe:/$ curl -i -H "Accept: application/json" -H "Content-Type: application/json" http://172.17.42.1:2376/containers/json
HTTP/1.1 200 OK
Content-Type: application/json
Server: Docker/1.9.1 (linux)
Date: Fri, 01 Apr 2016 22:52:15 GMT
Content-Length: 361

[{"Id":"10d22a5215fe86637d3922535e846e308d2d2ab7349a86627f17b2ed4aea2f15","Names":["/sharp_jennings"],"Image":"codenvy/che","ImageID":"d6bf60df45d9c121d848cf40432516994fc6b3b57857badba048e5f203cc3eab","Command":"bash","Created":1459551103,"Ports":[{"PrivatePort":8080,"Type":"tcp"}],"Labels":{},"Status":"Up 31 seconds","HostConfig":{"NetworkMode":"default"}}]
user@10d22a5215fe:/$ curl -i -H "Accept: application/json" -H "Content-Type: application/json" http://172.17.42.1:2376/containers/10d22a5215fe86637d3922535e846e308d2d2ab7349a86627f17b2ed4aea2f15/json
HTTP/1.1 200 OK
Content-Type: application/json
Server: Docker/1.9.1 (linux)
Date: Fri, 01 Apr 2016 22:52:25 GMT
Transfer-Encoding: chunked

{"Id":"10d22a5215fe86637d3922535e846e308d2d2ab7349a86627f17b2ed4aea2f15","Created":"2016-04-01T22:51:43.787016234Z","Path":"bash","Args":[],"State":{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":20165,"ExitCode":0,"Error":"","StartedAt":"2016-04-01T22:51:44.299574838Z","FinishedAt":"0001-01-01T00:00:00Z"},"Image":"d6bf60df45d9c121d848cf40432516994fc6b3b57857badba048e5f203cc3eab","ResolvConfPath":"/var/lib/docker/containers/10d22a5215fe86637d3922535e846e308d2d2ab7349a86627f17b2ed4aea2f15/resolv.conf","HostnamePath":"/var/lib/docker/containers/10d22a5215fe86637d3922535e846e308d2d2ab7349a86627f17b2ed4aea2f15/hostname","HostsPath":"/var/lib/docker/containers/10d22a5215fe86637d3922535e846e308d2d2ab7349a86627f17b2ed4aea2f15/hosts","LogPath":"/var/lib/docker/containers/10d22a5215fe86637d3922535e846e308d2d2ab7349a86627f17b2ed4aea2f15/10d22a5215fe86637d3922535e846e308d2d2ab7349a86627f17b2ed4aea2f15-json.log","Name":"/sharp_jennings","RestartCount":0,"Driver":"devicemapper","ExecDriver":"native-0.2","MountLabel":"","ProcessLabel":"","AppArmorProfile":"","ExecIDs":null,"HostConfig":{"Binds":null,"ContainerIDFile":"","LxcConf":[],"Memory":0,"MemoryReservation":0,"MemorySwap":0,"KernelMemory":0,"CpuShares":0,"CpuPeriod":0,"CpusetCpus":"","CpusetMems":"","CpuQuota":0,"BlkioWeight":0,"OomKillDisable":false,"MemorySwappiness":-1,"Privileged":false,"PortBindings":{},"Links":null,"PublishAllPorts":false,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"VolumesFrom":null,"Devices":[],"NetworkMode":"default","IpcMode":"","PidMode":"","UTSMode":"","CapAdd":null,"CapDrop":null,"GroupAdd":null,"RestartPolicy":{"Name":"no","MaximumRetryCount":0},"SecurityOpt":null,"ReadonlyRootfs":false,"Ulimits":null,"LogConfig":{"Type":"json-file","Config":{}},"CgroupParent":"","ConsoleSize":[0,0],"VolumeDriver":"","ShmSize":67108864},"GraphDriver":{"Name":"devicemapper","Data":{"DeviceId":"222","DeviceName":"docker-253:0-52373275-10d22a5215fe86637d3922535e846e308d2d2ab7349a86627f17b2ed4aea2f15","DeviceSize":"107374182400"}},"Mounts":[],"Config":{"Hostname":"10d22a5215fe","Domainname":"","User":"user","AttachStdin":true,"AttachStdout":true,"AttachStderr":true,"ExposedPorts":{"8080/tcp":{}},"Tty":true,"OpenStdin":true,"StdinOnce":true,"Env":["DOCKER_HOST=tcp://10.0.3.15:2375","PATH=/opt/jre1.8.0_65/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","JAVA_VERSION=8u65","JAVA_VERSION_PREFIX=1.8.0_65","CHE_LOCAL_CONF_DIR=/home/user/.che","JAVA_HOME=/opt/jre1.8.0_65"],"Cmd":["bash"],"Image":"codenvy/che","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{},"StopSignal":"SIGTERM"},"NetworkSettings":{"Bridge":"","SandboxID":"ca46fec71a9bf645da22cb2660f29d243ac9d4b4c18c5de67b597fcb4a686b73","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{"8080/tcp":null},"SandboxKey":"/var/run/docker/netns/ca46fec71a9b","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"a9b48913f8653b39f227fae949f87d11428e4a865f12d7d15a5e79e38f21efb6","Gateway":"172.17.42.1","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"172.17.0.1","IPPrefixLen":16,"IPv6Gateway":"","MacAddress":"02:42:ac:11:00:01","Networks":{"bridge":{"EndpointID":"a9b48913f8653b39f227fae949f87d11428e4a865f12d7d15a5e79e38f21efb6","Gateway":"172.17.42.1","IPAddress":"172.17.0.1","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:01"}}}}
user@10d22a5215fe:/$ 
user@10d22a5215fe:/$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
user@10d22a5215fe:/$

**Comment by DevarajAmarnath** [comment]
Yup. Updating docker on my VM did the trick. Thank you very much for your help @eivantsov . Now I'm waiting for the CDT team to support CDT in Che. :)

**Comment by magick93** [comment]
I am also getting the same error, being:

```
!!!
!!! Running 'docker' succeeded, but 'docker ps' failed. This usually means that docker cannot reach its daemon.
!!!
```

I am trying to run Che from the following docker-compose file. Note, I tried adding DOCKER_HOST env var but still get the same error.

```
che:
  image: codenvy/che
  command: >
    bash -c "
    sudo rm -rf /home/user/che/lib-copy/* &&
    sudo rm -rf /home/user/che/tomcat/temp/local-storage/* &&
    mkdir -p /home/user/che/lib-copy/ &&
    sudo chown -R user:user /home/user/che &&
    cp -rf /home/user/che/lib/* /home/user/che/lib-copy &&
    /home/user/che/bin/che.sh run -d
    "
  environment:
    DOCKER_HOST: tcp://172.17.0.1:2375
  net: "host"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/user/workspaces:/home/user/che/lib-copy"
    - "/home/user/workspaces/tradeworks.indicators:/home/user/che/workspaces"
    - "/home/user/workspaces/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage"
  container_name: che

```

**Comment by TylerJewell** [comment]
@magick93 - This compose file is now out of date.  I think the docs haven't been reverted against the new ones.  Can you take a look at the compose file located in the 4.3 docs here.

https://eclipse-che.readme.io/v4.3/docs/usage-docker#section-docker-compose

**Comment by tengkongyixu** [comment]
@eivantsov I have the same problem. My OS is CentOS6.7, docker version is 1.7.1
after installing by comman "yum install docker", i run the command "docker run -it -p 8080:8080 -p 49152-49162:49152-49162 codenvy/che". The image downloads succeed, but the error occurd.

I have tried change docker.sock and add enviroment var DOCKER_OPTS , but it still not work. what i can do to fix the problem?

thanks

**Comment by TylerJewell** [comment]
@tengkongyixu - I believe you are using outdated syntax in attempting to run Che as a docker container.  Please see the latest docs for running docker at: https://eclipse-che.readme.io/v4.3/docs/usage-docker.

**Comment by tengkongyixu** [comment]
@TylerJewell thanks for your answer！！ I have tried ，but still failed . I write down what happend ,please help me !

**1. check centos release**
[root@localhost ~]# cat /etc/centos-release
CentOS release 6.8 (Final)
The CentOS release is not 6.7, but I think it's not important at all.

**2. check docker service status**
[root@localhost ~]# service docker status
docker (pid  1423) is running...

**3. run che** 
[root@localhost ~]# docker run --net=host --name che -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/storage:/home/user/che/storage codenvy/che
Error response from daemon: Conflict. The name "che" is already in use by container fc0577a730ac. You have to delete (or rename) that container to be able to reuse that name.
[root@localhost ~]# docker run --net=host --name che2 -v /var/run/docker.sock:/var/run/doc
ker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/
user/che/workspaces -v /home/user/che/storage:/home/user/che/storage codenvy/che

!!!
!!! Running 'docker' succeeded, but 'docker ps' failed. This usually means that docker cannot reach its daemon.
!!! `

**4. check files in /home/user/che**
[root@localhost che]# ll
total 16
drwxr-xr-x 4 1000 1000 4096 Jun  7 09:05 lib
drwxr-xr-x 2 1000 1000 4096 Jun  7 08:55 storage
drwxr-xr-x 3 root root 4096 Jun  6 18:49 tomcat
drwxr-xr-x 2 1000 1000 4096 Jun  6 18:49 workspaces

I did the forth because when I　write command I found there was no directory /home/user/che/lib-copy 

thanks

**Comment by tengkongyixu** [comment]
@TylerJewell The versin of che is 1.7.1 ,so i think i should use the command "docker run --privileged -it -p 8080:8080 -p 49152-49162:49152-49162 codenvy/che" in the web site : "https://eclipse-che.readme.io/v1.0/docs/install-using-docker"

when I use that , this error messge occured: "[root@localhost ~]# docker run --privileged -it -p 8080:8080 -p 49152-49162:49152-49162 codenvy/che
Error response from daemon: Cannot start container 5d56d5a6b7ee76b3bdc68629de183ff86c6f7746fc55c3ce9df70b3c03daaa9f: iptables failed: iptables -t nat -A DOCKER -p tcp -d 0/0 --dport 49162 -j DNAT --to-destination 172.17.0.8:49162 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)"

and then i run che use "docker run -it -p 8080:8080 -p 49152-49162:49152-49162 codenvy/che" this error message occured "[root@localhost ~]# docker run -it -p 8080:8080 -p 49152-49162:49152-49162 codenvy/che
Error response from daemon: Cannot start container 18ce5668848d6b0fcf5bfd1b22793ad93f4755baabbdcfaf0337edbc14138e3f: iptables failed: iptables -t nat -A DOCKER -p tcp -d 0/0 --dport 49162 -j DNAT --to-destination 172.17.0.12:49162 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)"

**Comment by TylerJewell** [comment]
Your syntax for running Che in the first post was correct.  You get the `docker ps` issue in two situations:
1. `/var/run/docker.sock` doesn't have rw permissions.  Use `chmod 666 /var/run/docker.sock`.
2. The version of the docker client does not match the version of the docker daemon.  Che in the container is using a docker client that then calls out to the docker daemon on your host.

Try running a newer version of Che container to see what happens.

```
docker run --net=host --name che2 -v /var/run/docker.sock:/var/run/doc
ker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/
user/che/workspaces -v /home/user/che/storage:/home/user/che/storage codenvy/che:nightly
```

**Comment by tengkongyixu** [comment]
@TylerJewell Thanks for your patient and right answer!! 
**first,** i use `chmod 666 /var/run/docker.sock` to change the rw permissions of docker.sock
srw-rw-rw-  1 root root    0 Jun  7 13:02 docker.sock

**and then**  i run the command you said , this error occured:

"[root@localhost run]# docker run --net=host --name che2 -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/storage:/home/user/che/storage codenvy/che:nightly

!!!
!!! Running 'docker' succeeded, but 'docker ps' failed. \nThe file /var/run/docker.sock does not have appropriate permissions. \nOWNER READ:  r \nOWNER WRITE: w \nGROUP READ:  r \nGROUP WRITE: w \nOTHER READ:  r \nOTHER WRITE: w \nRun 'sudo chmod 666 /var/run/docker.sock' to give the right permissions.
!!!
"

**Comment by TylerJewell** [comment]
That is curious, indeed.

But you know what the issue is?  It's not you - it's a bug in the launching script.  I can go into what the issue is, but it's a really silly typo.  The issue is not related to the /var/run/docker.sock issues.  Chances are the docker client / docker server versions do not match.  I've committed a fix and the nightly Docker container for Eclipse Che will be updated shortly.  If you run it a bit later you will not run into this issue.

Out of curiosity - what does the following return?

```
docker version --format '{{.Server.Version}}
docker version --format '{{.Client.Version}}
```

**Comment by tengkongyixu** [comment]
@TylerJewell Thanks for your answer again!!!

The command `docker version --format '{{.Server.Version}}` not work, it returned this : 
"[root@localhost ~]# docker version --format '{{.Server.Version}}
 ">"

And then we tried `docker version --format '{{.Server.Verson}}'` , it returned this:
"flag provided but not defined: --format
See 'docker version --help'."

We tried `docker version --help` and this message shown:
"[root@localhost ~]# docker version --help

Usage: docker version [OPTIONS]

Show the Docker version information.

  --help=false       Print usage"

So I tried command `docker version` and it returned 
"Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64"

Both the Client Version and Server Version are 1.7.1.

**Comment by TylerJewell** [comment]
Ok.  Thanks.  I am fairly certain that the docker client that is inside the Che container that you are running is running docker 1.11.1.

The docker client in the container connects to the docker server on your computer which is 1.7.1.  This the difference.

**Comment by tengkongyixu** [comment]
@TylerJewell So I just need to update the client version of docker to 1.11.1, everything will be ok?

**Comment by TylerJewell** [comment]
Update docker engine on your host to 1.11.1 and then run the docker container with the run syntax using codenvy/che:nightly.

**Comment by tengkongyixu** [comment]
@TylerJewell Thank you very much！ 

I updated docker engine to 1.11.2, and ererything is ok on centos 7.

But when i click CTRL+C , che  can't stop?
and on contos 6 it is difficult to install docker engine 1.11.2, i want to know, weather centos 6 supports che 1.11.2?

**Comment by TylerJewell** [comment]
You need to reach out to Docker forums to discuss their OS / engine
compatibility matrix.  We test Che primarily on CentOS 7.x.

The docker syntax is launching Che in detached mode, with restart=always.
You need to use docker stop and other syntax to stop the container, remove
it, start it again.  You have launched Che as a server that will always be
restarted by Docker.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by tengkongyixu** [comment]
@TylerJewell Thanks for your help!!

**Comment by taylor-benson** [comment]
Running the latest nightly on mac also gets this issue.

Steps taken
1. export DOCKER_VM_IP=$(docker run --rm --net host alpine sh -c "ip a show eth0" | \
                   grep 'inet ' | cut -d/ -f1 | awk '{ print $2}')
2. sudo ifconfig lo0 alias $DOCKER_VM_IP
3. docker run --name=che \
   -v /Volumes/workspace/che/lib:/home/user/che/lib-copy \
   -v /Volumes/workspace/che/workspaces:/home/user/che/workspaces \
   -v /Volumes/workspace/che/storage:/home/user/che/storage \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -p 8080:8080 \
   codenvy/che:nightly --remote:$DOCKER_VM_IP

(Volumes workspace is my local dir)

docker version --format '{{.Server.Version}}'
1.12.0-rc4

docker version --format '{{.Client.Version}}'
1.12.0-rc4

Sorry to post on a closed issue. If you want I can open a new one.

**Comment by l0rd** [comment]
@taylor-benson I'm not able to reproduce your problem. Can you try to update your nightly:

``` bash
docker pull codenvy/che:nightly
```

and then retry?

**Comment by taylor-benson** [comment]
Thanks, pulling the latest got rid of the docker.sock permissions. Ran into the following when starting up my workspace, unzip:  cannot find or open /mnt/che/ws-agent.zip, /mnt/che/ws-agent.zip.zip or /mnt/che/ws-agent.zip.ZIP.

I'll comb back over the docs to see if I missed something. This seems like a really cool tool and very interested in showing my dev teams this platform.
