### ISSUE TITLE
Workspace creation fails on openshift origin 1.7. Cannot connect to wsagent.

### ISSUE THREAD

**Issue by ivanthelad** [eclipse-che/che#7960]
### Description

After folllowing the steps outlined here https://www.eclipse.org/che/docs/setup/openshift/index.html the che server comes up without issue. When a workspace is created. che server created the workspace pod and corrosponding routes. after around 2 mins the che server will remove all these resources and fail with the message that it cannot connect to the wsagent. 

Log messages 
`2017-12-19 12:59:15,366[aceSharedPool-1]  [ERROR] [o.e.c.a.agent.WsAgentLauncher 147]   - Fail pinging ws agent with https://wsagent-n331rct3lbmne1sz-che-che5.52.166.222.111.nip.io/api/ url in workspacen331rct3lbmne1sz workspace in machineq6nc88ywajp73axv machine on localhost node.
2017-12-19 12:59:15,386[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 96]   - Removing OpenShift Route codeserver-n331rct3lbmne1sz
2017-12-19 12:59:15,394[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 96]   - Removing OpenShift Route exec-agent-n331rct3lbmne1sz
2017-12-19 12:59:15,399[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 96]   - Removing OpenShift Route server-4403-tcp-n331rct3lbmne1sz
2017-12-19 12:59:15,406[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 96]   - Removing OpenShift Route ssh-n331rct3lbmne1sz
2017-12-19 12:59:15,419[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 96]   - Removing OpenShift Route terminal-n331rct3lbmne1sz
2017-12-19 12:59:15,425[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 96]   - Removing OpenShift Route tomcat8-debug-n331rct3lbmne1sz
2017-12-19 12:59:15,435[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 96]   - Removing OpenShift Route tomcat8-n331rct3lbmne1sz
2017-12-19 12:59:15,443[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 96]   - Removing OpenShift Route wsagent-n331rct3lbmne1sz
2017-12-19 12:59:15,449[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 102]  - Removing OpenShift Service che-ws-n331rct3lbmne1sz
2017-12-19 12:59:15,476[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 107]  - Removing OpenShift Deployment che-ws-n331rct3lbmne1sz
2017-12-19 12:59:15,606[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 112]  - Removing OpenShift ReplicaSets for deployment che-ws-n331rct3lbmne1sz
2017-12-19 12:59:15,660[aceSharedPool-1]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java:153)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:681)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:800)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
2017-12-19 13:01:29,893[aceSharedPool-2]  [WARN ] [.e.c.p.d.m.MachineProviderImpl 569]  - Failed to check image eclipse/ubuntu_jdk8 availability. Cause: Unable connect to unix socket: '/var/run/docker.sock'
2017-12-19 13:01:31,919[aceSharedPool-2]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1029] - Created ImageStream eclipse_ubuntu_jdk8.
2017-12-19 13:01:35,943[aceSharedPool-2]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1795] - Created ImageStreamTag eclipse_ubuntu_jdk8:n72llhqi4kztaqimdpz3sq49qxdavs48 in namespace che5
2017-12-19 13:01:35,944[aceSharedPool-2]  [WARN ] [o.e.c.p.o.c.OpenShiftConnector 563]  - Didn't find image 'eclipse-che/workspacen72llhqi4kztaqim_machinedpz3sq49qxdavs48_che_dev-machine' in the map of created images
2017-12-19 13:01:35,954[aceSharedPool-2]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1587] - imageStreamTag dockerImageConfig empty. Using dockerImageMetadata to get image info
2017-12-19 13:01:35,977[aceSharedPool-2]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1587] - imageStreamTag dockerImageConfig empty. Using dockerImageMetadata to get image info
2017-12-19 13:01:35,977[aceSharedPool-2]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 647]  - Che property 'che.openshift.workspace.memory.override' used to override workspace memory limit to 1900Mi.`

### Reproduction Steps
Deploy stanadard multi mode  origin deployment. with che deployed as outlined by the steps above

**OS and version:**    
centos 7.4
origin 1.7
**Diagnostics:**

**Comment by l0rd** [comment]
@ivanthelad what's in the logs before the fail to ping message? Does it says that wsagent is started? Has the route been created (e.g. `oc get routes`)?

**Comment by ivanthelad** [comment]
what we see is the che server comes up successfully. 
We can create a workspace. 
the problem is the che server kills the workspace after a few minutes. This is due to agent not repsonding in time. 
if i jump into the workspace pod using oc rsh and perform a curl against the local agent endpoint (http://localhost:4401)i  receive a 404 back from tomcat 
I may be wrong but we suspect the workspace is not given enough time to start up and would like to know how to configure the che server to allow the workspace time to come up. 

I came across these configs in the config map but as far i could tell from the entry point script they are not referenced and the entrypoint always initialize the server on the default vales 

che-wsagent-ping-success-threshold: "600"
  che.workspace.agent.dev.ping_conn_timeout_ms: "6000"
  che.workspace.agent.dev.ping_delay_ms: "6000"
  che.workspace.agent.dev.ping_success_threshold: "100"

**Comment by ivanthelad** [comment]
yes the routes has been created 
:). The server successfuly stops the workspace pod and delete the created routes afterward

**Comment by ivanthelad** [comment]
btw, i was able to apply configuration to ensure the che server waited a bit longer. this allowed be to see that the tomcat instance listening on port 4401 is successfully started but there is not application deployed. despite the logs out stating it came up 
 
both the route/serviceVIP/podIP return all the same default tomcat 404 page. 

FYI, i also have configured my che deployment without SSL(trying to eliminate all issues)

under 
/home/user/che/ws-agent/logs/logs



`catalina.log  localhost-access.log
$ cat catalina.log
2017-12-19 20:08:23,015[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.5.11
2017-12-19 20:08:23,018[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Jan 10 2017 21:02:52 UTC
2017-12-19 20:08:23,018[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.5.11.0
2017-12-19 20:08:23,019[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2017-12-19 20:08:23,019[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-693.11.1.el7.x86_64
2017-12-19 20:08:23,019[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2017-12-19 20:08:23,019[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
2017-12-19 20:08:23,020[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11
2017-12-19 20:08:23,020[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2017-12-19 20:08:23,020[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
2017-12-19 20:08:23,020[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
2017-12-19 20:08:23,020[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
2017-12-19 20:08:23,021[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2017-12-19 20:08:23,021[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseG1GC
2017-12-19 20:08:23,021[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseStringDeduplication
2017-12-19 20:08:23,021[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MinHeapFreeRatio=20
2017-12-19 20:08:23,021[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxHeapFreeRatio=40
2017-12-19 20:08:23,021[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxRAM=1200m
2017-12-19 20:08:23,022[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
2017-12-19 20:08:23,022[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
2017-12-19 20:08:23,022[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
2017-12-19 20:08:23,022[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djuli-logback.configurationFile=file:/home/user/che/ws-agent/conf/tomcat-logger.xml
2017-12-19 20:08:23,022[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
2017-12-19 20:08:23,022[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
2017-12-19 20:08:23,023[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
2017-12-19 20:08:23,023[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2017-12-19 20:08:23,023[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2017-12-19 20:08:23,023[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2017-12-19 20:08:23,023[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
2017-12-19 20:08:23,023[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
2017-12-19 20:08:23,024[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
2017-12-19 20:08:23,024[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
2017-12-19 20:08:23,126[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 525]  - Initializing ProtocolHandler ["http-nio-4401"]
2017-12-19 20:08:23,187[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read
2017-12-19 20:08:23,190[main]             [INFO ] [o.a.catalina.startup.Catalina 617]   - Initialization processed in 582 ms
2017-12-19 20:08:23,204[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
2017-12-19 20:08:23,205[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service Catalina
2017-12-19 20:08:23,205[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.11
2017-12-19 20:08:23,354[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
2017-12-19 20:08:28,630[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 5,275 ms
2017-12-19 20:08:28,633[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 570]  - Starting ProtocolHandler [http-nio-4401]
2017-12-19 20:08:28,639[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 5449 ms`

**Comment by ivanthelad** [comment]
more info, below is the output from the che server UI console
`[STDOUT] Terminal Agent binary is downloaded remotely
[STDOUT] 2017/12/19 22:01:29 Terminal-agent configuration
[STDOUT] 2017/12/19 22:01:29   Server
[STDOUT] 2017/12/19 22:01:29     - Address: :4411
[STDOUT] 2017/12/19 22:01:29     - Base path: ''
[STDOUT] 2017/12/19 22:01:29   Terminal
[STDOUT] 2017/12/19 22:01:29     - Slave command: ''
[STDOUT] 2017/12/19 22:01:29     - Activity tracking enabled: true
[STDOUT] 2017/12/19 22:01:29   Workspace master server
[STDOUT] 2017/12/19 22:01:29     - API endpoint: http://che-host:8080/wsmaster/api
[STDOUT] 2017/12/19 22:01:29 
[STDOUT] 2017/12/19 22:01:29 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2017/12/19 22:01:29 Terminal routes:
[STDOUT] 2017/12/19 22:01:29 ✓ Connect to pty(websocket) ............... GET    /pty
[STDOUT] 2017/12/19 22:01:29 
[STDOUT] Exec Agent binary is downloaded remotely
[STDOUT] 2017/12/19 22:01:36 Exec-agent configuration
[STDOUT] 2017/12/19 22:01:36   Server
[STDOUT] 2017/12/19 22:01:36     - Address: :4412
[STDOUT] 2017/12/19 22:01:36     - Base path: ''
[STDOUT] 2017/12/19 22:01:36   Process executor
[STDOUT] 2017/12/19 22:01:36     - Logs dir: /home/user/che/exec-agent/logs
[STDOUT] 2017/12/19 22:01:36 
[STDOUT] 2017/12/19 22:01:36 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2017/12/19 22:01:36 Process Routes:
[STDOUT] 2017/12/19 22:01:36 ✓ Start Process ........................... POST   /process
[STDOUT] 2017/12/19 22:01:36 ✓ Get Process ............................. GET    /process/:pid
[STDOUT] 2017/12/19 22:01:36 ✓ Kill Process ............................ DELETE /process/:pid
[STDOUT] 2017/12/19 22:01:36 ✓ Get Process Logs ........................ GET    /process/:pid/logs
[STDOUT] 2017/12/19 22:01:36 ✓ Get Processes ........................... GET    /process
[STDOUT] 2017/12/19 22:01:36 
[STDOUT] 2017/12/19 22:01:36 Exec-Agent WebSocket routes:
[STDOUT] 2017/12/19 22:01:36 ✓ Connect to Exec-Agent(websocket) ........ GET    /connect
[STDOUT] 2017/12/19 22:01:36 
[STDOUT] 2017/12/19 22:01:36 ⇩ Registered RPCRoutes:
[STDOUT] 
[STDOUT] 2017/12/19 22:01:36 Process Routes:
[STDOUT] 2017/12/19 22:01:36 ✓ process.start
[STDOUT] 2017/12/19 22:01:36 ✓ process.kill
[STDOUT] 2017/12/19 22:01:36 ✓ process.subscribe
[STDOUT] 2017/12/19 22:01:36 ✓ process.unsubscribe
[STDOUT] 2017/12/19 22:01:36 ✓ process.updateSubscriber
[STDOUT] 2017/12/19 22:01:36 ✓ process.getLogs
[STDOUT] 2017/12/19 22:01:36 ✓ process.getProcess
[STDOUT] 2017/12/19 22:01:36 ✓ process.getProcesses
[STDOUT] Workspace Agent will be downloaded from Workspace Master
[STDOUT] Listening for transport dt_socket at address: 4403`

**Comment by garagatyi** [comment]
@ivanthelad FYI a URL that is mapped in ws-agent and doesn't return 404 is `http://localhost:4401/api/`
Returning 404 for URLs `http://localhost:4401`, `http://localhost:4401/` and even `http://localhost:4401/api` is expected behavior.

**Comment by l0rd** [comment]
@ivanthelad that's a network problem: the wsmaster cannot connect to the wsagent for some reason. My guess is that you set the wrong `OPENSHIFT_NAMESPACE_URL` (maybe a dot is missing?):

```diff
- che-che5.52.166.222.111.nip.io
+ che-che.5.52.166.222.111.nip.io
```

but to confirm you should compare the url you get in the logs  (e.g. https://wsagent-n331rct3lbmne1sz-che-che5.52.166.222.111.nip.io) with the url of the wsagent route.

**Comment by ivanthelad** [comment]
@l0rd good catch. but unfortunately that wasn't the issue. i deployed a few instances of che before i created this issue and perhaps in my haste that typo creeped in. despite this the behaviour is the same. 
all routes/vips/podips are accessible.  from the che server and likewise from the workspace pod to che-server are also accessible. 

From what i can see its hanging on downloading wsagent. this is guess based on the logs. do you know of anything that might stop it from downloading the agent. The logs from the che server. it will hang here until che-server kills the workspace pod.

`[STDOUT] Exec Agent binary is downloaded remotely
[STDOUT] 2017/12/20 17:16:37 Exec-agent configuration
[STDOUT] 2017/12/20 17:16:37   Server
[STDOUT] 2017/12/20 17:16:37     - Address: :4412
[STDOUT] 2017/12/20 17:16:37     - Base path: ''
[STDOUT] 2017/12/20 17:16:37   Process executor
[STDOUT] 2017/12/20 17:16:37     - Logs dir: /home/user/che/exec-agent/logs
[STDOUT] 2017/12/20 17:16:37 
[STDOUT] 2017/12/20 17:16:37 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2017/12/20 17:16:37 Process Routes:
[STDOUT] 2017/12/20 17:16:37 ✓ Start Process ........................... POST   /process
[STDOUT] 2017/12/20 17:16:37 ✓ Get Process ............................. GET    /process/:pid
[STDOUT] 2017/12/20 17:16:37 ✓ Kill Process ............................ DELETE /process/:pid
[STDOUT] 2017/12/20 17:16:37 ✓ Get Process Logs ........................ GET    /process/:pid/logs
[STDOUT] 2017/12/20 17:16:37 ✓ Get Processes ........................... GET    /process
[STDOUT] 2017/12/20 17:16:37 
[STDOUT] 2017/12/20 17:16:37 Exec-Agent WebSocket routes:
[STDOUT] 2017/12/20 17:16:37 ✓ Connect to Exec-Agent(websocket) ........ GET    /connect
[STDOUT] 2017/12/20 17:16:37 
[STDOUT] 2017/12/20 17:16:37 ⇩ Registered RPCRoutes:
[STDOUT] 
[STDOUT] 2017/12/20 17:16:37 Process Routes:
[STDOUT] 2017/12/20 17:16:37 ✓ process.start
[STDOUT] 2017/12/20 17:16:37 ✓ process.kill
[STDOUT] 2017/12/20 17:16:37 ✓ process.subscribe
[STDOUT] 2017/12/20 17:16:37 ✓ process.unsubscribe
[STDOUT] 2017/12/20 17:16:37 ✓ process.updateSubscriber
[STDOUT] 2017/12/20 17:16:37 ✓ process.getLogs
[STDOUT] 2017/12/20 17:16:37 ✓ process.getProcess
[STDOUT] 2017/12/20 17:16:37 ✓ process.getProcesses
[STDOUT] Terminal Agent binary is downloaded remotely
[STDOUT] 2017/12/20 17:16:44 Terminal-agent configuration
[STDOUT] 2017/12/20 17:16:44   Server
[STDOUT] 2017/12/20 17:16:44     - Address: :4411
[STDOUT] 2017/12/20 17:16:44     - Base path: ''
[STDOUT] 2017/12/20 17:16:44   Terminal
[STDOUT] 2017/12/20 17:16:44     - Slave command: ''
[STDOUT] 2017/12/20 17:16:44     - Activity tracking enabled: true
[STDOUT] 2017/12/20 17:16:44   Workspace master server
[STDOUT] 2017/12/20 17:16:44     - API endpoint: http://che-host:8080/wsmaster/api
[STDOUT] 2017/12/20 17:16:44 
[STDOUT] 2017/12/20 17:16:44 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2017/12/20 17:16:44 Terminal routes:
[STDOUT] 2017/12/20 17:16:44 ✓ Connect to pty(websocket) ............... GET    /pty
[STDOUT] 2017/12/20 17:16:44 
[STDOUT] Workspace Agent will be downloaded from Workspace Master
[STDOUT] Listening for transport dt_socket at address: 4403` 

I tried downloading the agent manually from within the pod curl and using the local dns name che-host. this wasn't a issue as it has connectivity. can you point me in area where i could debug the process of downloading the agent. eg, where to look. there doesn'T seem to be any logs produced. 


Another point, is. i'm trying to deploy the standard stacks included in che.  i assume these should work, right?. as the process outlined in the deploy on openshift steps i found outline importing RH specific stacks(this are behind a wall anyway, called devregistry). i doubt this is a factor right?

**Comment by ivanthelad** [comment]
@l0rd is there a way to make the che-server wait longer for the workspace to come up. i've see a wsagent threshold value in the configmap.would that suffice? 
i tried setting this before but i think the entire value is ignored

update: i notice when i jump into the che-workspace that is created. the environment variable  referenced 
$WORKSPACE_MASTER_URI is not set 
https://github.com/eclipse/che/blob/e1d894939c44b8c21b18bbd8615d3fb18b458168/wsagent/agent/src/main/resources/installers/1.0.1/org.eclipse.che.ws-agent.script.sh#L43

**Comment by l0rd** [comment]
@ivanthelad you copy/paste the logs of the wsagent and it looks like it has been started successfully (and therefore downloaded successfully too).

From the same logs I see that wsagent has been started in 6 seconds. That's much less than the default timeout so I am afraid that augmenting the timeout won't help. 

The new wsagent success ping threshold property is the minimum number of successful, consecutive, pings the che server will wait before considering wsagent has been started fine.  The default should be `1` (https://github.com/eclipse/che/blob/5.22.x/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L113) so, if you haven't changed it, your Che server never receives one successful ping from the wsagent.

Have you tried to ping `http://localhost:4401/api/` as suggested by @garagatyi ?

Having a look at errors that may appear in your browser javascript console may help too.

**Comment by ivanthelad** [comment]
@l0rd  @garagatyi 

from within the che-workspace i can curl that endpoint. i can also curl it from the che-server (using svc , route or pod-ip) 
curl http://localhost:4401/
<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.11 - Error report</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style> </head><body><h1>HTTP Status 404 - /</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.11</h3></body></html>$

**Comment by l0rd** [comment]
@ivanthelad you meant `curl http://localhost:4401/api/` right? Because the `/api/` part is still missing in your answer...

**Comment by ghost** [comment]
@ivanthelad can you reproduce it with the latest nightly? Here are some docs to follow https://www.eclipse.org/che/docs/6/che/docs/openshift.html

**Comment by eivantsov** [comment]
@ivanthelad any update on this one please?

**Comment by patlachance** [comment]
@ivanthelad could you please explain how you manage to configure the che.workspace.agent.dev.ping* properties?

**Comment by eivantsov** [comment]
@ivanthelad i am closing this issue due to inactivity. Feel free to reopen but make sure you get Che 6.x version
